"use client";
import Head from "next/head";
import {
  AiFillLinkedin,
  AiFillGithub,
  AiOutlineMail
} from "react-icons/ai";
import { BiUpArrowCircle } from "react-icons/bi";
import deved from "../../public/dev-ed-wave.png";
import Image from "next/image";
import Kavan from "../../public/Kavan.png"

export default function Home() {
  return (
      <div>
        <html className=" scroll-smooth"></html>
        <Head>
          <title>Kavan Thakkar Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href='/favico.ico'></link>
        </Head>
        <body>
        <nav className=' py-5 px-40 flex justify-center md:justify-between gap-2 bg-gray-900 sticky top-0'>
              <h1 className=" text-opacity-0 md:text-opacity-100 md:text-3xl font-serif font-bold">Portfolio</h1>
              <h1 className="md:text-transparent">|</h1>
              <ul className='flex gap-1 md:gap-2 font-serif'>
                <li>
                  <button className="px-2 text-sm md:px-5 rounded-full hover:text-black hover:bg-teal-500 md:text-xl"><a href="#">Home</a></button>
                </li>
                <li>
                  <button className="px-2 text-sm md:px-5 rounded-full hover:text-black hover:bg-teal-500 md:text-xl"><a href="#about">About</a></button>
                </li>
                <li>
                  <button className="px-2 text-sm md:px-5 rounded-full hover:text-black hover:bg-teal-500 md:text-xl"><a href="#skill">Skills</a></button>
                </li>
                <li>
                  <button className="px-2 text-sm md:px-5 rounded-full hover:text-black hover:bg-teal-500 md:text-xl"><a href="#contact">Contact</a></button>
                </li>
              </ul>
            </nav>
        <main className='bg-gradient-to-b from-gray-900 via-gray-400 to-white px-10 text-white md:px-20 lg:px-40 font-serif scroll-smooth py-20'>
          <section id="home" className=' min-h-screen'>
            {/* <nav className=' py-10 mb-12 flex justify-center md:justify-between gap-2'>
              <h1 className=" text-opacity-0 md:text-opacity-100 md:text-3xl font-serif font-bold">Portfolio</h1>
              <h1 className="md:text-transparent">|</h1>
              <ul className='flex gap-1 md:gap-2'>
                <li>
                  <button className="px-2 text-sm md:px-5 rounded-full hover:text-white hover:bg-teal-500 md:text-xl">Home</button>
                </li>
                <li>
                  <button className="px-2 text-sm md:px-5 rounded-full hover:text-white hover:bg-teal-500 md:text-xl"><a href="#about">About</a></button>
                </li>
                <li>
                  <button className="px-2 text-sm md:px-5 rounded-full hover:text-white hover:bg-teal-500 md:text-xl"><a href="#skill">Skills</a></button>
                </li>
                <li>
                  <button className="px-2 text-sm md:px-5 rounded-full hover:text-white hover:bg-teal-500 md:text-xl"><a href="#contact">Contact</a></button>
                </li>
              </ul>
            </nav> */}
            <div className="xl:flex lg:pt-11">
              <div>
                <div className='text-center p-10'>
                  <h2 className='text-6xl 2xl:text-8xl xl:text-7xl py-10 text-teal-600 font-bold md:text-6xl lg:text-6xl'>Kavan Thakkar</h2>
                  <h3 className='text-3xl py-2 md:text-3xl xl:text-4xl font-semibold'>Developer and designer,</h3>
                  <p className='text-lg py-5 text-black md:text-lg xl:text-xl max-w-xl mx-auto'>Third year student at Birla Institute of Technology and Science, Pilani and a front-end development enthusiast. Let's connect!</p>
                  <button className=" bg-gradient-to-b from-orange-600 to-orange-400 py-1 px-5 rounded-lg text-xl font-bold mt-3">Resume</button>
                </div>
                {/* <div className='flex text-5xl justify-center gap-1 py-3 text-white'>
                  <AiFillTwitterCircle/>
                <AiFillLinkedin/>
                <AiFillYoutube/>
                </div> */}
              </div>
              <div className='relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 mx-auto overflow-hidden'>
                <Image src={deved} layout='fill' objectFit='cover' />
              </div>
            </div>
          </section>
          <section id="about" className="pt-24 min-h-screen">
            <div>
              <h3 className='text-7xl py1 font-bold text-teal-500 text-center'>About Me</h3>
              <p className='text-xl py-2 leading-8 text-black mt-8 text-center'>
              My name is Kavan Thakkar. I am pursuing a dual degree in <span className="text-black font-extrabold">MSc Physics</span> and <span className="text-black font-extrabold">B.E. Electronics and
              Instrumentation</span>. I have fundamental knowledge of web development and am currently mastering
              React.js. As a part of the <span className="text-black font-extrabold">GDSC BITS Pilani chapter's core team</span>, I have gained invaluable expertise in leadership, teamwork, and cutting-edge technology. I am passionate about keeping up of the latest developments in my profession and utilising them to produce excellent results.
              </p>
              <p className="text-xl text-black">
              </p>
            </div>
            <div className="lg:flex gap-10">
              <div className="shadow-lg bg-opacity-50 bg-white p-10 rounded-xl my-10 basis-1/2">
                <h1 className="text-3xl text-center md:text-left text-orange-600 font-extrabold">Education:</h1>
                <ul className="list-disc text-black">
                  <li className="py-2">
                    <div className="">
                      <h2 className="text-black text-xl py-1 font-bold">Delhi Public School, Bopal, Ahmedabad</h2>
                      <h2 className="text-black text-xl">(2007-2019)</h2>
                    </div>
                    <p className="text-lg text-gray-800">10th grade: 95.7%</p>
                  </li>
                  <li className="py-2">
                    <div className="">
                      <h2 className="text-black text-xl py-1 font-bold">Rahul International School, Nallasopara, Palghar</h2>
                      <h2 className="text-black text-xl">(2019-2021)</h2>
                    </div>
                    <p className="text-lg text-gray-800">12th grade: 93.2%</p>
                  </li>
                  <li className="py-2">
                    <div className="">
                      <h2 className="text-black text-xl py-1 font-bold">Birla Institute of Technology and Sciences, Pilani, Rajasthan</h2>
                      <h2 className="text-black text-xl">(2021-pesent)</h2>
                    </div>
                    <p className="text-lg text-gray-800">Cumulative Grade: 7.05</p>
                  </li>
                </ul>
              </div>
              <div className="shadow-lg bg-opacity-50 bg-white p-10 rounded-xl my-10 basis-1/2">
                <h1 className="text-3xl text-center md:text-left text-orange-600 font-extrabold">Experience:</h1>
                <ul className=" list-disc text-black">
                  <li className="py-2">
                    <div className="">
                      <h2 className="text-black text-xl py-1 font-extrabold">Google Developer Student Clubs, BITS Pilani</h2>
                      <h2 className="text-black text-xl">(2021-present)</h2>
                    </div>
                    <h2 className="text-gray-800 text-xl py-1 font-bold">Positions:</h2>
                    <p className="text-lg text-gray-800 py-0.5">Core Team Member (Dec 2022 - present)</p>
                    <p className="text-lg text-gray-800 py-0.5">Front-end development team lead (Feb 2023 - present)</p>
                    <h2 className="text-gray-800 text-lg py-1 font-bold">Skills Gathered:</h2>
                    <p className="text-gray-700 py-1">React.js, Vue.js, Vuetify, WAMP, HTML, HTML5, Cascading Style Sheets (CSS), JavaScript, Python (Programming Language), MySQL, Version Control</p>
                  </li>
                  <li className="py-2">
                    <div className="">
                      <h2 className="text-black text-xl py-1 font-extrabold">Bhaskaracharya Institute for Space Applications and Geoinformatics (BISAG-N), Gandhinagar</h2>
                      <h2 className="text-black text-xl">(June 2023-August 2023)</h2>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </section>
          <section id="skill" className="pt-24 min-h-screen">
            <div>
              <h3 className='text-7xl py-1 text-teal-500 font-bold text-center'>Skills</h3>
            </div>
            <h1 className="text-xl py-2 leading-8 text-black mt-8 text-center">I started my path as a front-end developer 1 year ago and since then, I have worked with many tool like:</h1>
            <div className="shadow-lg bg-opacity-30 bg-white p-5 rounded-xl my-10">
            </div>
          </section>
        </main>
        </body>
        <section id="contact" className="bg-teal-500 min-h-screen">
          <div>
            <h1 className="text-5xl text-center md:text-left md:text-8xl text-orange-600 font-extrabold px-20 md:px-40 pt-24">You think we have things in common?</h1>
            <h2 className="text-black text-4xl px-20 md:px-40 pt-5 text-center md:text-left">Drop me a message on any of my socials!!</h2>
            {/* <div className="flex justify-center items-center">
              <Image src={Kavan} className="rounded-full h-72 w-72"></Image>
            </div> */}
          </div>
          {/* <div className="px-40">
            <Image src={Kavan} className="rounded-full" />
          </div> */}
          <div className="px-20 md:px-40 text-center font-serif md:flex md:items-center md:justify-between md:text-left pt-36">
          <Image src={Kavan} className="rounded-full h-56 w-56 md:h-64 md:w-64 mx-auto md:mx-0"></Image>
          <div className="pb-10">
            <h1 className="pb-2 pt-10 text-black text-3xl font-bold">Kavan Thakkar</h1>
            <h2 className="text-black text-xl"><span className="font-bold">Phone Number:</span> 9925141357</h2>
            <h2 className="text-black text-xl"><span className="font-bold">Mail:</span> kavan1357@gmail.com</h2>
            <h2 className="text-black text-xl"><span className="font-bold">Residence:</span> Surat, India</h2>
            <div className="flex pt-7 text-black text-3xl gap-8 items-center justify-center sm:items-left sm:justify-center">
              <a className="hover:text-white" href="https://github.com/Ka1Thakkar" target="_blank"><AiFillGithub /></a>
              <a className="hover:text-white" href="https://www.linkedin.com/in/kavan-thakkar/" target="_blank"><AiFillLinkedin /></a>
              <a className="hover:text-white" href="mailto:kavan1357@gmail.com" target="_blank"><AiOutlineMail /></a>
            </div>
          </div>
          {/* <a href="#"><BiUpArrowCircle className="text-black text-5xl md:text-7xl mx-auto cursor-pointer hover:text-white hover:bg-teal-800 hover:rounded-full"/></a> */}
          </div>
          <a href="#"><BiUpArrowCircle className="text-black text-5xl md:text-7xl mx-auto cursor-pointer hover:text-white hover:bg-teal-800 hover:rounded-full"/></a>
        </section>
      </div>
  )
}
